bgp_address_family:
    address_family:
    -   afi: ipv4
        neighbor:
        -   activate: true
            address: 172.31.39.212
            soft_reconfiguration: true
        network:
        -   address: 192.0.2.0
        -   address: 192.0.3.0
        -   address: 192.0.4.0
    as_number: '65536'
bgp_global:
    as_number: '65536'
    bgp:
        log_neighbor_changes: true
        router_id:
            address: 172.31.47.175
    neighbor:
    -   address: 172.31.39.212
        remote_as: 65536
