bgp_address_family:
    address_family:
    -   afi: ipv4
        neighbor:
        -   activate: true
            address: 172.31.32.213
        -   activate: true
            address: 172.31.35.140
        network:
        -   address: 198.51.100.0
    as_number: '65536'
bgp_global:
    as_number: '65536'
    bgp:
        log_neighbor_changes: true
    neighbor:
    -   address: 172.31.32.213
        remote_as: 65536
    -   address: 172.31.35.140
        remote_as: 65536
    -   activate: true
        address: 172.31.32.213
    -   activate: true
        address: 172.31.35.140
