bgp_address_family:
    address_family:
    -   afi: ipv4
        networks:
        -   network: 203.0.113.0/24
        safi: unicast
    as_number: '65536'
bgp_global:
    as_number: '65536'
    bgp:
        router_id: 172.31.35.140
    neighbors:
    -   neighbor: 172.31.32.213
        remote_as: 65536
    -   neighbor: 172.31.34.28
        remote_as: 65536
bgp_neighbor_address_family:
    as_number: '65536'
    neighbors:
    -   address_family:
        -   afi: ipv4
            safi: unicast
            weight: 200
        neighbor_address: 172.31.32.213
    -   address_family:
        -   afi: ipv4
            safi: unicast
            weight: 200
        neighbor_address: 172.31.34.28
