---
- hosts: all
  gather_facts: no
  tasks:
    - name: Init CSRv-1
      cisco.ios.ios_config:
        lines:
          - "router bgp 65536"
          - "no network 192.0.3.0"
          - "no network 192.0.4.0"
        match: none
      when: inventory_hostname == "csrv-1"
    
    - name: Init CSRv-2
      cisco.ios.ios_config:
        lines:
          - "router bgp 65536"
          - "no network 198.51.101.0"
          - "no network 198.51.102.0"
        match: none
      when: inventory_hostname == "csrv-2"
