---
- hosts: all
  gather_facts: no
  tasks:
    - name: "Parse BGP routes recevied"
      ansible.utils.cli_parse:
        command: show ip route bgp
        parser:
          name: ansible.netcommon.pyats
      register: result

    - name: "Validate BGP Routes received"
      ansible.utils.validate:
        data: "{{ result['parsed'] }}"
        criteria:
          - "{{ lookup('file',  'bgp_schema/{{ inventory_hostname }}.json') | from_json }}"
        engine: ansible.utils.jsonschema

